export const HEROES = [
  { id: 1, name: "antimage", localizedName: "Anti-Mage", primaryAttr: "agi", attackType: "Melee", roles: ["Carry", "Escape", "Nuker"] },
  { id: 2, name: "axe", localizedName: "Axe", primaryAttr: "str", attackType: "Melee", roles: ["Initiator", "Durable", "Disabler", "Jungler"] },
  { id: 3, name: "bane", localizedName: "Bane", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Disabler", "Nuker", "Durable"] },
  { id: 4, name: "bloodseeker", localizedName: "Bloodseeker", primaryAttr: "agi", attackType: "Melee", roles: ["Carry", "Jungler", "Nuker", "Disabler"] },
  { id: 5, name: "crystal_maiden", localizedName: "Crystal Maiden", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Disabler", "Nuker", "Jungler"] },
  { id: 6, name: "drow_ranger", localizedName: "Drow Ranger", primaryAttr: "agi", attackType: "Ranged", roles: ["Carry", "Disabler", "Pusher"] },
  { id: 7, name: "earthshaker", localizedName: "Earthshaker", primaryAttr: "str", attackType: "Melee", roles: ["Support", "Initiator", "Disabler", "Nuker"] },
  { id: 8, name: "juggernaut", localizedName: "Juggernaut", primaryAttr: "agi", attackType: "Melee", roles: ["Carry", "Pusher", "Escape"] },
  { id: 9, name: "mirana", localizedName: "Mirana", primaryAttr: "agi", attackType: "Ranged", roles: ["Carry", "Support", "Escape", "Nuker", "Disabler"] },
  { id: 10, name: "morphling", localizedName: "Morphling", primaryAttr: "agi", attackType: "Ranged", roles: ["Carry", "Escape", "Durable", "Nuker", "Disabler"] },
  { id: 11, name: "nevermore", localizedName: "Shadow Fiend", primaryAttr: "agi", attackType: "Ranged", roles: ["Carry", "Nuker"] },
  { id: 12, name: "phantom_lancer", localizedName: "Phantom Lancer", primaryAttr: "agi", attackType: "Melee", roles: ["Carry", "Escape", "Pusher", "Nuker"] },
  { id: 13, name: "puck", localizedName: "Puck", primaryAttr: "int", attackType: "Ranged", roles: ["Initiator", "Disabler", "Escape", "Nuker"] },
  { id: 14, name: "pudge", localizedName: "Pudge", primaryAttr: "str", attackType: "Melee", roles: ["Disabler", "Initiator", "Durable", "Nuker"] },
  { id: 15, name: "razor", localizedName: "Razor", primaryAttr: "agi", attackType: "Ranged", roles: ["Carry", "Durable", "Nuker", "Pusher"] },
  { id: 16, name: "sand_king", localizedName: "Sand King", primaryAttr: "str", attackType: "Melee", roles: ["Initiator", "Disabler", "Support", "Nuker", "Escape"] },
  { id: 17, name: "storm_spirit", localizedName: "Storm Spirit", primaryAttr: "int", attackType: "Ranged", roles: ["Carry", "Escape", "Nuker", "Initiator", "Disabler"] },
  { id: 18, name: "sven", localizedName: "Sven", primaryAttr: "str", attackType: "Melee", roles: ["Carry", "Disabler", "Initiator", "Durable", "Nuker"] },
  { id: 19, name: "tiny", localizedName: "Tiny", primaryAttr: "str", attackType: "Melee", roles: ["Carry", "Nuker", "Pusher", "Initiator", "Durable", "Disabler"] },
  { id: 20, name: "vengefulspirit", localizedName: "Vengeful Spirit", primaryAttr: "agi", attackType: "Ranged", roles: ["Support", "Initiator", "Disabler", "Nuker", "Escape"] },
  { id: 21, name: "windrunner", localizedName: "Windranger", primaryAttr: "int", attackType: "Ranged", roles: ["Carry", "Support", "Disabler", "Escape", "Nuker"] },
  { id: 22, name: "zuus", localizedName: "Zeus", primaryAttr: "int", attackType: "Ranged", roles: ["Nuker", "Carry"] },
  { id: 23, name: "kunkka", localizedName: "Kunkka", primaryAttr: "str", attackType: "Melee", roles: ["Carry", "Support", "Disabler", "Initiator", "Durable", "Nuker"] },
  { id: 25, name: "lina", localizedName: "Lina", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Carry", "Nuker", "Disabler"] },
  { id: 26, name: "lion", localizedName: "Lion", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Disabler", "Nuker", "Initiator"] },
  { id: 27, name: "shadow_shaman", localizedName: "Shadow Shaman", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Pusher", "Disabler", "Nuker", "Initiator"] },
  { id: 28, name: "slardar", localizedName: "Slardar", primaryAttr: "str", attackType: "Melee", roles: ["Carry", "Durable", "Initiator", "Disabler", "Escape"] },
  { id: 29, name: "tidehunter", localizedName: "Tidehunter", primaryAttr: "str", attackType: "Melee", roles: ["Initiator", "Durable", "Disabler", "Nuker", "Carry"] },
  { id: 30, name: "witch_doctor", localizedName: "Witch Doctor", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Nuker", "Disabler"] },
  { id: 31, name: "lich", localizedName: "Lich", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Nuker"] },
  { id: 32, name: "riki", localizedName: "Riki", primaryAttr: "agi", attackType: "Melee", roles: ["Carry", "Escape", "Disabler"] },
  { id: 33, name: "enigma", localizedName: "Enigma", primaryAttr: "int", attackType: "Ranged", roles: ["Initiator", "Disabler", "Jungler", "Pusher"] },
  { id: 34, name: "tinker", localizedName: "Tinker", primaryAttr: "int", attackType: "Ranged", roles: ["Carry", "Nuker", "Pusher"] },
  { id: 35, name: "sniper", localizedName: "Sniper", primaryAttr: "agi", attackType: "Ranged", roles: ["Carry", "Nuker"] },
  { id: 36, name: "necrolyte", localizedName: "Necrophos", primaryAttr: "int", attackType: "Ranged", roles: ["Carry", "Nuker", "Durable", "Disabler"] },
  { id: 37, name: "warlock", localizedName: "Warlock", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Initiator", "Disabler"] },
  { id: 38, name: "beastmaster", localizedName: "Beastmaster", primaryAttr: "str", attackType: "Melee", roles: ["Initiator", "Disabler", "Durable", "Nuker"] },
  { id: 39, name: "queenofpain", localizedName: "Queen of Pain", primaryAttr: "int", attackType: "Ranged", roles: ["Carry", "Nuker", "Escape"] },
  { id: 40, name: "venomancer", localizedName: "Venomancer", primaryAttr: "agi", attackType: "Ranged", roles: ["Support", "Nuker", "Initiator", "Pusher", "Disabler"] },
  { id: 41, name: "faceless_void", localizedName: "Faceless Void", primaryAttr: "agi", attackType: "Melee", roles: ["Carry", "Initiator", "Disabler", "Escape", "Durable"] },
  { id: 42, name: "skeleton_king", localizedName: "Wraith King", primaryAttr: "str", attackType: "Melee", roles: ["Carry", "Support", "Durable", "Disabler"] },
  { id: 43, name: "death_prophet", localizedName: "Death Prophet", primaryAttr: "int", attackType: "Ranged", roles: ["Carry", "Pusher", "Nuker", "Disabler"] },
  { id: 44, name: "phantom_assassin", localizedName: "Phantom Assassin", primaryAttr: "agi", attackType: "Melee", roles: ["Carry", "Escape"] },
  { id: 45, name: "pugna", localizedName: "Pugna", primaryAttr: "int", attackType: "Ranged", roles: ["Nuker", "Pusher"] },
  { id: 46, name: "templar_assassin", localizedName: "Templar Assassin", primaryAttr: "agi", attackType: "Ranged", roles: ["Carry", "Escape"] },
  { id: 47, name: "viper", localizedName: "Viper", primaryAttr: "agi", attackType: "Ranged", roles: ["Carry", "Durable", "Initiator", "Disabler"] },
  { id: 48, name: "luna", localizedName: "Luna", primaryAttr: "agi", attackType: "Ranged", roles: ["Carry", "Nuker", "Pusher"] },
  { id: 49, name: "dragon_knight", localizedName: "Dragon Knight", primaryAttr: "str", attackType: "Melee", roles: ["Carry", "Pusher", "Durable", "Disabler", "Initiator", "Nuker"] },
  { id: 50, name: "dazzle", localizedName: "Dazzle", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Nuker", "Disabler"] },
  { id: 51, name: "rattletrap", localizedName: "Clockwerk", primaryAttr: "str", attackType: "Melee", roles: ["Initiator", "Disabler", "Durable", "Nuker"] },
  { id: 52, name: "leshrac", localizedName: "Leshrac", primaryAttr: "int", attackType: "Ranged", roles: ["Carry", "Support", "Nuker", "Pusher", "Disabler"] },
  { id: 53, name: "furion", localizedName: "Nature's Prophet", primaryAttr: "int", attackType: "Ranged", roles: ["Carry", "Jungler", "Pusher", "Escape", "Nuker"] },
  { id: 54, name: "life_stealer", localizedName: "Lifestealer", primaryAttr: "str", attackType: "Melee", roles: ["Carry", "Durable", "Jungler", "Escape", "Disabler"] },
  { id: 55, name: "dark_seer", localizedName: "Dark Seer", primaryAttr: "int", attackType: "Melee", roles: ["Initiator", "Jungler", "Escape", "Disabler"] },
  { id: 56, name: "clinkz", localizedName: "Clinkz", primaryAttr: "agi", attackType: "Ranged", roles: ["Carry", "Escape", "Pusher"] },
  { id: 57, name: "omniknight", localizedName: "Omniknight", primaryAttr: "str", attackType: "Melee", roles: ["Support", "Durable", "Nuker"] },
  { id: 58, name: "enchantress", localizedName: "Enchantress", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Jungler", "Pusher", "Durable", "Disabler"] },
  { id: 59, name: "huskar", localizedName: "Huskar", primaryAttr: "str", attackType: "Ranged", roles: ["Carry", "Durable", "Initiator"] },
  { id: 60, name: "night_stalker", localizedName: "Night Stalker", primaryAttr: "str", attackType: "Melee", roles: ["Carry", "Initiator", "Durable", "Disabler", "Nuker"] },
  { id: 61, name: "broodmother", localizedName: "Broodmother", primaryAttr: "agi", attackType: "Melee", roles: ["Carry", "Pusher", "Escape", "Nuker"] },
  { id: 62, name: "bounty_hunter", localizedName: "Bounty Hunter", primaryAttr: "agi", attackType: "Melee", roles: ["Escape", "Nuker"] },
  { id: 63, name: "weaver", localizedName: "Weaver", primaryAttr: "agi", attackType: "Ranged", roles: ["Carry", "Escape"] },
  { id: 64, name: "jhakiro", localizedName: "Jakiro", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Nuker", "Pusher", "Disabler"] },
  { id: 65, name: "batrider", localizedName: "Batrider", primaryAttr: "int", attackType: "Ranged", roles: ["Initiator", "Disabler", "Escape"] },
  { id: 66, name: "chen", localizedName: "Chen", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Jungler", "Pusher"] },
  { id: 67, name: "spectre", localizedName: "Spectre", primaryAttr: "agi", attackType: "Melee", roles: ["Carry", "Durable", "Escape"] },
  { id: 68, name: "ancient_apparition", localizedName: "Ancient Apparition", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Disabler", "Nuker"] },
  { id: 69, name: "doom_bringer", localizedName: "Doom", primaryAttr: "str", attackType: "Melee", roles: ["Carry", "Disabler", "Initiator", "Durable", "Nuker"] },
  { id: 70, name: "ursa", localizedName: "Ursa", primaryAttr: "agi", attackType: "Melee", roles: ["Carry", "Jungler", "Durable", "Disabler"] },
  { id: 71, name: "spirit_breaker", localizedName: "Spirit Breaker", primaryAttr: "str", attackType: "Melee", roles: ["Carry", "Initiator", "Disabler", "Durable", "Escape"] },
  { id: 72, name: "gyrocopter", localizedName: "Gyrocopter", primaryAttr: "agi", attackType: "Ranged", roles: ["Carry", "Nuker", "Disabler"] },
  { id: 73, name: "alchemist", localizedName: "Alchemist", primaryAttr: "str", attackType: "Melee", roles: ["Carry", "Support", "Durable", "Disabler", "Initiator", "Nuker"] },
  { id: 74, name: "invoker", localizedName: "Invoker", primaryAttr: "int", attackType: "Ranged", roles: ["Carry", "Nuker", "Disabler", "Escape", "Pusher"] },
  { id: 75, name: "silencer", localizedName: "Silencer", primaryAttr: "int", attackType: "Ranged", roles: ["Carry", "Support", "Initiator", "Disabler"] },
  { id: 76, name: "obsidian_destroyer", localizedName: "Outworld Destroyer", primaryAttr: "int", attackType: "Ranged", roles: ["Carry", "Nuker", "Disabler"] },
  { id: 77, name: "lycan", localizedName: "Lycan", primaryAttr: "str", attackType: "Melee", roles: ["Carry", "Pusher", "Jungler", "Durable", "Escape"] },
  { id: 78, name: "brewmaster", localizedName: "Brewmaster", primaryAttr: "str", attackType: "Melee", roles: ["Carry", "Initiator", "Durable", "Disabler", "Nuker"] },
  { id: 79, name: "shadow_demon", localizedName: "Shadow Demon", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Disabler", "Initiator", "Nuker"] },
  { id: 80, name: "lone_druid", localizedName: "Lone Druid", primaryAttr: "agi", attackType: "Ranged", roles: ["Carry", "Pusher", "Jungler", "Durable"] },
  { id: 81, name: "chaos_knight", localizedName: "Chaos Knight", primaryAttr: "str", attackType: "Melee", roles: ["Carry", "Disabler", "Durable", "Pusher"] },
  { id: 82, name: "meepo", localizedName: "Meepo", primaryAttr: "agi", attackType: "Melee", roles: ["Carry", "Nuker", "Disabler", "Escape", "Pusher"] },
  { id: 83, name: "treant", localizedName: "Treant Protector", primaryAttr: "str", attackType: "Melee", roles: ["Support", "Initiator", "Durable", "Disabler"] },
  { id: 84, name: "ogre_magi", localizedName: "Ogre Magi", primaryAttr: "int", attackType: "Melee", roles: ["Support", "Nuker", "Disabler", "Durable", "Initiator"] },
  { id: 85, name: "undying", localizedName: "Undying", primaryAttr: "str", attackType: "Melee", roles: ["Support", "Durable", "Disabler", "Nuker"] },
  { id: 86, name: "rubick", localizedName: "Rubick", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Disabler", "Nuker"] },
  { id: 87, name: "disruptor", localizedName: "Disruptor", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Disabler", "Nuker", "Initiator"] },
  { id: 88, name: "nyx_assassin", localizedName: "Nyx Assassin", primaryAttr: "agi", attackType: "Melee", roles: ["Disabler", "Nuker", "Initiator", "Escape"] },
  { id: 89, name: "naga_siren", localizedName: "Naga Siren", primaryAttr: "agi", attackType: "Melee", roles: ["Carry", "Support", "Pusher", "Disabler", "Initiator", "Escape"] },
  { id: 90, name: "keeper_of_the_light", localizedName: "Keeper of the Light", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Nuker", "Disabler", "Escape"] },
  { id: 91, name: "wisp", localizedName: "Io", primaryAttr: "str", attackType: "Ranged", roles: ["Support", "Escape", "Nuker"] },
  { id: 92, name: "visage", localizedName: "Visage", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Nuker", "Durable", "Disabler", "Pusher"] },
  { id: 93, name: "slark", localizedName: "Slark", primaryAttr: "agi", attackType: "Melee", roles: ["Carry", "Escape", "Disabler", "Nuker"] },
  { id: 94, name: "medusa", localizedName: "Medusa", primaryAttr: "agi", attackType: "Ranged", roles: ["Carry", "Disabler", "Durable"] },
  { id: 95, name: "troll_warlord", localizedName: "Troll Warlord", primaryAttr: "agi", attackType: "Ranged", roles: ["Carry", "Pusher", "Disabler", "Durable"] },
  { id: 96, name: "centaur", localizedName: "Centaur Warrunner", primaryAttr: "str", attackType: "Melee", roles: ["Durable", "Initiator", "Disabler", "Nuker", "Escape"] },
  { id: 97, name: "magnataur", localizedName: "Magnus", primaryAttr: "str", attackType: "Melee", roles: ["Initiator", "Disabler", "Nuker", "Escape"] },
  { id: 98, name: "shredder", localizedName: "Timbersaw", primaryAttr: "str", attackType: "Melee", roles: ["Nuker", "Durable", "Escape"] },
  { id: 99, name: "bristleback", localizedName: "Bristleback", primaryAttr: "str", attackType: "Melee", roles: ["Carry", "Durable", "Initiator", "Nuker"] },
  { id: 100, name: "tusk", localizedName: "Tusk", primaryAttr: "str", attackType: "Melee", roles: ["Initiator", "Disabler", "Nuker"] },
  { id: 101, name: "skywrath_mage", localizedName: "Skywrath Mage", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Nuker", "Disabler"] },
  { id: 102, name: "abaddon", localizedName: "Abaddon", primaryAttr: "str", attackType: "Melee", roles: ["Support", "Carry", "Durable"] },
  { id: 103, name: "elder_titan", localizedName: "Elder Titan", primaryAttr: "str", attackType: "Melee", roles: ["Initiator", "Disabler", "Nuker", "Durable"] },
  { id: 104, name: "legion_commander", localizedName: "Legion Commander", primaryAttr: "str", attackType: "Melee", roles: ["Carry", "Disabler", "Initiator", "Durable", "Nuker"] },
  { id: 105, name: "techies", localizedName: "Techies", primaryAttr: "int", attackType: "Ranged", roles: ["Nuker", "Disabler"] },
  { id: 106, name: "ember_spirit", localizedName: "Ember Spirit", primaryAttr: "agi", attackType: "Melee", roles: ["Carry", "Escape", "Nuker", "Disabler", "Initiator"] },
  { id: 107, name: "earth_spirit", localizedName: "Earth Spirit", primaryAttr: "str", attackType: "Melee", roles: ["Nuker", "Escape", "Disabler", "Initiator", "Durable"] },
  { id: 108, name: "abyssal_underlord", localizedName: "Underlord", primaryAttr: "str", attackType: "Melee", roles: ["Support", "Nuker", "Disabler", "Durable", "Escape"] },
  { id: 109, name: "terrorblade", localizedName: "Terrorblade", primaryAttr: "agi", attackType: "Melee", roles: ["Carry", "Pusher", "Nuker"] },
  { id: 110, name: "phoenix", localizedName: "Phoenix", primaryAttr: "str", attackType: "Ranged", roles: ["Support", "Nuker", "Initiator", "Escape", "Disabler"] },
  { id: 111, name: "oracle", localizedName: "Oracle", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Nuker", "Disabler", "Escape"] },
  { id: 112, name: "winter_wyvern", localizedName: "Winter Wyvern", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Disabler", "Nuker"] },
  { id: 113, name: "arc_warden", localizedName: "Arc Warden", primaryAttr: "agi", attackType: "Ranged", roles: ["Carry", "Escape", "Nuker"] },
  { id: 114, name: "monkey_king", localizedName: "Monkey King", primaryAttr: "agi", attackType: "Melee", roles: ["Carry", "Escape", "Disabler", "Initiator"] },
  { id: 119, name: "dark_willow", localizedName: "Dark Willow", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Nuker", "Disabler", "Escape"] },
  { id: 120, name: "pangolier", localizedName: "Pangolier", primaryAttr: "agi", attackType: "Melee", roles: ["Carry", "Nuker", "Disabler", "Escape", "Initiator"] },
  { id: 121, name: "grimstroke", localizedName: "Grimstroke", primaryAttr: "int", attackType: "Ranged", roles: ["Support", "Nuker", "Disabler", "Escape"] },
  { id: 123, name: "snapfire", localizedName: "Snapfire", primaryAttr: "str", attackType: "Ranged", roles: ["Support", "Nuker", "Disabler", "Escape"] },
  { id: 126, name: "void_spirit", localizedName: "Void Spirit", primaryAttr: "int", attackType: "Melee", roles: ["Carry", "Escape", "Nuker", "Disabler"] },
  { id: 128, name: "snapfire", localizedName: "Snapfire", primaryAttr: "str", attackType: "Ranged", roles: ["Support", "Nuker", "Disabler", "Escape"] },
  { id: 129, name: "mars", localizedName: "Mars", primaryAttr: "str", attackType: "Melee", roles: ["Initiator", "Carry", "Disabler", "Durable"] },
  { id: 135, name: "dawnbreaker", localizedName: "Dawnbreaker", primaryAttr: "str", attackType: "Melee", roles: ["Carry", "Durable"] },
  { id: 136, name: "marci", localizedName: "Marci", primaryAttr: "str", attackType: "Melee", roles: ["Support", "Carry", "Initiator", "Disabler", "Escape"] },
  { id: 137, name: "primal_beast", localizedName: "Primal Beast", primaryAttr: "str", attackType: "Melee", roles: ["Initiator", "Durable", "Disabler"] },
  { id: 138, name: "muerta", localizedName: "Muerta", primaryAttr: "int", attackType: "Ranged", roles: ["Carry", "Nuker", "Disabler"] },
]

export const TI2026_EUROPE_TEAMS = [
  { id: 1001, name: "Team Spirit", tag: "TSpirit", region: "EU" },
  { id: 1002, name: "PARIVISION", tag: "PARI", region: "EU" },
  { id: 1003, name: "Nigma Galaxy", tag: "NGX", region: "EU" },
  { id: 1004, name: "NAVI", tag: "NAVI", region: "EU" },
  { id: 1005, name: "MOUZ", tag: "MOUZ", region: "EU" },
  { id: 1006, name: "Virtus.pro", tag: "VP", region: "EU" },
  { id: 1007, name: "Yellow Submarine", tag: "YeS", region: "EU" },
  { id: 1008, name: "Power Rangers", tag: "PR", region: "EU" },
  { id: 1009, name: "HULIGANI", tag: "HU", region: "EU" },
  { id: 1010, name: "L1GA TEAM", tag: "L1GA", region: "EU" },
  { id: 1011, name: "Team Bald", tag: "Bald", region: "EU" },
  { id: 1012, name: "MODUS", tag: "MODUS", region: "EU" },
  { id: 1013, name: "IC x Insanity", tag: "IC", region: "EU" },
  { id: 1014, name: "4ikibamboni", tag: "4iki", region: "EU" },
  { id: 1015, name: "VP.Prodigy", tag: "VP.P", region: "EU" },
  { id: 1016, name: "Rune Eaters", tag: "RE", region: "EU" },
  { id: 1017, name: "Enjoy", tag: "Enjoy", region: "EU" },
]

export const TI2026_NA_TEAMS = [
  { id: 2001, name: "GamerLegion", tag: "GL", region: "NA" },
  { id: 2002, name: "The Bug", tag: "Bug", region: "NA" },
  { id: 2003, name: "GGB", tag: "GGB", region: "NA" },
  { id: 2004, name: "4A+I", tag: "4AI", region: "NA" },
]
